// Code generated by protoc-gen-go. DO NOT EDIT.

package __

type HttpHelloRequest struct {
	Name string `json:"name,omitempty" param:"name" `
	Age  int32 `query:"age" `
	HelloRequest
}
type HttpHelloReply struct {
	Message string   `json:"message,omitempty" `
	Code int32  `json:"code,omitempty" `
}
