// Code generated by protoc-gen-go. DO NOT EDIT.

package __

type EchoHelloRequest struct {
	Name string `param:"name" json:"name,omitempty" `
	HelloRequest
}

type EchoHelloReply struct {
	Message string
	Code    int32
	HelloReply
}
